CREATE DATABASE `CsdlCongty` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */

CREATE TABLE PHONGBAN (
    MaPB INT PRIMARY KEY,
    TenPB VARCHAR(30) NOT NULL,
    MaQL CHAR(9),
    NgayBoNhiem DATE
);

CREATE TABLE DUAN (
    MaDA INT PRIMARY KEY,
    TenDA VARCHAR(30) NOT NULL,
    DiaDiem VARCHAR(50),
    MaPB INT,
    FOREIGN KEY (MaPB) REFERENCES PHONGBAN(MaPB)
);

CREATE TABLE NHANVIEN (
    MaNV CHAR(9) PRIMARY KEY,
    HoNV VARCHAR(15) NOT NULL,
    Dem VARCHAR(15),
    TenNV VARCHAR(15) NOT NULL,
    NgaySinh DATE,
    DiaChi VARCHAR(50),
    GioiTinh CHAR(1) CHECK (GioiTinh IN ('m', 'M', 'f', 'F')),
    Luong INT,
    MaGS CHAR(9),
    MaPB INT,
    FOREIGN KEY (MaGS) REFERENCES NHANVIEN(MaNV),
    FOREIGN KEY (MaPB) REFERENCES PHONGBAN(MaPB)
);

ALTER TABLE PHONGBAN ADD FOREIGN KEY (MaQL) REFERENCES NHANVIEN(MaNV);

CREATE TABLE TRUSO_PHONG (
    MaPB INT,
    TruSo VARCHAR(50),
    PRIMARY KEY (MaPB, TruSo),
    FOREIGN KEY (MaPB) REFERENCES PHONGBAN(MaPB)
);

CREATE TABLE THAMGIA (
	MaNV CHAR(9),
    MaDA INT,
    SoGio DECIMAL(6, 1),
    PRIMARY KEY (MaNV,MaDA),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV),
    FOREIGN KEY (MaDA) REFERENCES DUAN(MaDA)
);

CREATE TABLE THANNHAN (
    MaNV CHAR(9),
    TenTN VARCHAR(45),
    GioiTinh CHAR(1) CHECK (GioiTinh IN ('m', 'M', 'f', 'F')),
    NgaySinh DATE,
    QuanHe VARCHAR(10),
    PRIMARY KEY (MaNV, TenTN),
    FOREIGN KEY (MaNV) REFERENCES NHANVIEN(MaNV)
);
